---
- name: Ready Atomic host for Kubernetes master services
  hosts: masters
  remote_user: deploy
  become: true
  roles:
    - common
    - atomic-k8s-master-pre

- name: Ready Atomic host for Kubelet
  hosts: masters
  remote_user: deploy
  become: true
  roles:
    - common
