---
- name: restart k8s
  service:
    name: kube-apiserver
    state: restarted

- name: restart etcd
  service:
    name: etcd
    state: restarted

- name: reload systemd
  command: systemctl daemon-reload
