---
  # TODO - ML, remove insecure ports or limit to minion access
- name: Configure etcd LISTEN CLIENT URLS
  lineinfile:
    dest: /etc/etcd/etcd.conf
    line: ETCD_LISTEN_CLIENT_URLS="http://localhost:2379,http://localhost:4001,http://{{ ansible_default_ipv4.address }}:2379,http://{{ ansible_default_ipv4.address }}:4001"
    regexp: "^ETCD_LISTEN_CLIENT_URLS"
  notify: restart etcd

# TODO - ML, remove insecure ports or limit to minion access
- name: Configure etcd ADVERTISE CLIENTS
  lineinfile:
    dest: /etc/etcd/etcd.conf
    line: ETCD_ADVERTISE_CLIENT_URLS="http://localhost:2379,http://localhost:4001,http://{{ ansible_default_ipv4.address }}:2379,http://{{ ansible_default_ipv4.address }}:4001"
    regexp: "^ETCD_ADVERTISE_CLIENT_URLS"
  notify: restart etcd

# - name: Configure flanneld via etcd
# - name: Secure etcd
