---
- name: Configure k8s via /etc/kubernetes
  lineinfile:
    dest: "/etc/kubernetes/{{ item.name }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regex }}"
    state: present
    create: yes
  with_items:
    - { name: "config",
    regex: "^KUBE_ETCD_SERVERS", line: 'KUBE_ETCD_SERVERS="--etcd_servers=http://localhost:2379"' }
    - { name: "config", regex: "^KUBE_API_ADDRESS", line: 'KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range={{ cluster_subnet }}"' }
    - { name: "apiserver", regex: "^KUBE_API_ADDRESS", line: 'KUBE_API_ADDRESS="--address=0.0.0.0"' }
    - { name: "apiserver", regex: "^KUBE_API_ADDRESS", line: 'KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota,ServiceAccount"' }
    - { name: "apiserver", regex: "^KUBE_API_ARGS", line: 'KUBE_API_ARGS="--service_account_key_file={{ service_account_key_file }}"' }
    - { name: "controller-manager", regex: "^KUBE_CONTROLLER_MANAGER_ARGS", line: 'KUBE_CONTROLLER_MANAGER_ARGS="--service_account_key_file={{ service_account_key_file }}"' }
  notify: restart k8s

- name: Enable k8s services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
