---
- name: Configure k8s via /etc/kubernetes
  lineinfile:
    dest: "/etc/kubernetes/{{ item.name }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regex }}"
    state: present
    create: yes
  with_items:
    - { name: 'apiserver', regex: "^KUBE_API_ADDRESS", line: 'KUBE_API_ADDRESS="--insecure-bind-address=0.0.0.0"' }
  notify: restart k8sapi

- name: Configure the k8s dashboard
  command: /usr/bin/kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
  #TODO add when!

- name: Add port 8080 to iptables
  iptables:
    action: insert
    chain: KUBE-FIREWALL
    protocol: tcp
    destination_port: 8080
    jump: ACCEPT

- name: Save iptables
  command: /usr/sbin/service iptables save
  notify: restart iptables
